#!/bin/bash

# Set env

if [ ! -d "Labs/Lab$1" ]; then
    echo "Aborted! Lab$1 doesn't exits"
    echo "Usage: degub [LAB NUMBER (e.g. 05)]"
    exit 1
fi

cd Labs/Lab$1

mkdir -p Debug
cd Debug

# Build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make

# Run
# clear
# ./$(grep -E '^add_executable\(' ../CMakeLists.txt | awk -F'[()]' '{print $2}' | awk '{print $1}')
